### ISSUE TITLE
bsdf.cpp comments

### ISSUE THREAD

**Issue by pachiko** [CMU-Graphics/Scotty3D#4]
In bsdf.cpp, refract:
// When dot(out_dir,normal=(0,1,0)) is **positive**, then out_dir corresponds to a
    // ray exiting the surface into vaccum (ior = 1).

This is confusing, it contradicts the docs for task 6, which says: "If cos(out_dir, N=[0,1,0]) **< 0** then your code should assume the ray is leaving the surface and entering vacuum."

**Comment by yhesper** [comment]
Yes, this is a bit confusing. I believe the doc was referring to what it is going to be like when you reverse the light path to create the in-ray.
Could you please make your Scotty3D repo private to yourself in order to help us maintain the academic integrity of our class in the future? Many thanks!

**Comment by pachiko** [comment]
@yhesper I still don't get it.

In trace_ray, out_dir is always pointing away from the hit surface (ray.point - hit.position), even though the ray is moving away from the camera towards the surface.

So if out_dir has positive-y, then I suppose the ray in trace_ray is hitting the surface from vacuum, which also means the returned vector is within the denser medium?

If out_dir has negative-y, then the incoming ray is going from the medium out into vacuum, which means the returned vector is either within vacuum, or within the medium if total internal reflected?

![Untitled](https://user-images.githubusercontent.com/42316301/103146588-f36b0900-4786-11eb-8414-9dfad08770b1.png)

I have also made my repo private.

**Comment by yhesper** [comment]
your intuition is correct; what the doc was trying to say is that, to get _ret_ in your diagram, you can view as if there is a light going at the opposite direction as the _out_dir_, hit the surface, refract and give you the _ret_, and this is because light paths are reversible, and hence "If cos(out_dir, N=[0,1,0]) < 0 then your _code should assume_ the ray is leaving the surface and entering vacuum." Of course, the doc didn't do a great job explaining it, and we are planning to improve it.
